import ContactForm from "@/components/forms/ContactForm";
import Hero from "@/components/ui/Hero";

export const metadata = {
	title: "MyECOMMERCE - Contact",
	description: "Contact page meta: Generated by create next app",
	keywords: ["contact us", "contact", "get in touch", "contact"],
};

export default function ContactPage() {
	return (
		<div className="flex flex-col md:flex-row w-full md:h-full justify-around gap-8 items-center flex-grow">
			<div className="w-full md:w-1/3">
				<Hero
					aligned="left"
					title="Contact"
					styledWord=" us"
					subTitle="We'd love to hear from you! Please use this form to let us know what you need."
				/>
			</div>
			<div className="flex justify-center  bg-gray-600 border border-gray-600 rounded-lg  md:w-2/3 py-8 md:p-16">
				<ContactForm />
			</div>
		</div>
	);
}
