import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { CartProvider } from "@/contexts/CartContext";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "My Next.js Ecommerce template",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} flex flex-col container mx-auto`}
			>
				<AuthProvider>
					<CartProvider>
						<Header />
						<main className="flex min-h-[80vh] overflow-scroll flex-col items-center  px-5 md:px-0">
							{children}
						</main>
						{/* <Footer /> */}
					</CartProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
