import ProductList from "@/components/products/ProductList";
import { Suspense } from "react";
import { BeatLoader } from "react-spinners";

export const generateMetadata = async ({ params }) => {
	return {
		title: "MyECOMMERCE - " + params.category.toUpperCase(),
		description:
			params.category.toUpperCase() +
			" page meta: Generated by create next app",
		keywords: [
			"products",
			"tech",
			"setup gear",
			"desktop",
			"furniture",
			"monitors",
			"gadgets",
			"lightning",
		],
	};
};

const CategoryPage = async ({ params }) => {
	const { category } = params;

	return (
		<Suspense fallback={<CategoryPageLoader />}>
			<ProductList category={category} />
		</Suspense>
	);
};

export default CategoryPage;

//REACT SPINNER

const CategoryPageLoader = () => {
	return (
		<div className="flex flex-col gap-8 justify-center flex-grow items-center animate-pulse">
			<BeatLoader color="#fff" /> <p>Fetching products..</p>
		</div>
	);
};
